on:
  push:
    branches:
      - develop
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
      - name: Show GitHub context   
        env: 
          GITHUB_CONTEXT: ${{ github.triggering_actor }}   
        run: echo "$GITHUB_CONTEXT"
        shell: bash
