on:
  push:
    branches:
      - develop
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
      - name: Show GitHub context
        if: ${{ github.triggering_actor == 'ranjithvkechidna' }}
        run: echo 'test'
      - name: Test data  
        run: echo "Testing the data..."
        shell: bash
