on:
  push:
    branches:
      - develop
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
      - name: HubSpot CMS Deploy
        uses: HubSpot/hubspot-cms-deploy-action@v1.7
        with:
          src_dir: MyModules
          dest_dir: /MyModules
          portal_id: ${{ secrets.hubspot_portal_id }}
          personal_access_key: ${{ secrets.hubspot_personal_access_key }}